#!/usr/bin/env bash
# Train one shard of the 48-architecture 135M ground-truth set.
#
#   scripts/supernet/gt135_driver.sh <shard> <of>
#
# Resumable: an architecture whose output directory already holds arch.json is skipped, so a
# machine that dies mid-set resumes where it stopped and a shard can be re-run safely.
#
# Do NOT edit this file while it is running. bash reads a script incrementally, so rewriting it
# under a live loop corrupts the loop -- this project has already lost work that way.
set -uo pipefail
cd "$(dirname "$0")/../.."
export PYTHONPATH="$(pwd)/src${PYTHONPATH:+:$PYTHONPATH}"
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=false

SHARD=${1:?shard index}
OF=${2:?number of shards}
STEPS=${STEPS:-2000}
LR=${LR:-3e-3}          # measured, not assumed: 3e-4 4.936 / 1e-3 3.711 / 3e-3 3.366 /
                        # 1e-2 3.536 / 3e-2 7.002 (diverged), held-out CE at ctx 1024
MIX=${MIX:-sl_fineweb=0.40,sl_code=0.25,sl_math=0.20,sl_rag=0.15}
OUT=${OUT:-runs/supernet/gt135}

mkdir -p logs/supernet "$OUT"
python experiments/supernet_fidelity/gt135_set.py --shard "$SHARD" --of "$OF" | while read -r NAME SHAPE; do
  if [ -f "$OUT/$NAME/arch.json" ]; then
    echo "[skip] $NAME already trained"; continue
  fi
  echo "=== $NAME  shape $SHAPE  lr $LR  steps $STEPS ==="
  python experiments/supernet_fidelity/groundtruth.py --model smollm2-135m --shape "$SHAPE" --arch "$NAME" \
    --steps "$STEPS" --batch 2 --accum 8 --lr "$LR" --mix "$MIX" --init base --out "$OUT" \
    || echo "[FAIL] $NAME"
done
echo "=== shard $SHARD/$OF done ==="
